const aksimsDisplayNames = {
  'Alabama State': 'Alabama St.',
  'Alabama-Birmingham': 'UAB',
  'Albany (NY)': 'Albany',
  'Alcorn State': 'Alcorn St.',
  'Appalachian State': 'Appalachian St.',
  'Arizona State': 'Arizona St.',
  'Arkansas State': 'Arkansas St.',
  'Arkansas-Pine Bluff': 'Pine Bluff',
  'Ball State': 'Ball St.',
  'Boise State': 'Boise St.',
  'Boston University': 'Boston U',
  'Bowling Green State': 'Bowling Green',
  'Brigham Young': 'BYU',
  'Cal State Bakersfield': 'CSU-Bakersfield',
  'Cal State Fullerton': 'CSU-Fullerton',
  'Cal State Northridge': 'CSU-Northridge',
  'California Baptist': 'Cal Baptist',
  'Central Connecticut State': 'Central Conn. St.',
  'Central Florida': 'UCF',
  'Charleston Southern': 'Charleston So.',
  'Chicago State': 'Chicago St.',
  'Cleveland State': 'Cleveland St.',
  'College of Charleston': 'Charleston',
  'Colorado State': 'Colorado St.',
  'Connecticut': 'UConn',
  'Coppin State': 'Coppin St.',
  'Delaware State': 'Delaware St.',
  'Detroit Mercy': 'Detroit',
  'East Tennessee State': 'East Tenn. St.',
  'Florida State': 'Florida St.',
  'Fresno State': 'Fresno St.',
  'Idaho State': 'Idaho St.',
  'Illinois State': 'Illinois St.',
  'Illinois-Chicago': 'UIC',
  'Indiana State': 'Indiana St.',
  'Iowa State': 'Iowa St.',
  'Jackson State': 'Jackson St.',
  'Jacksonville State': 'Jacksonville St.',
  'Kansas State': 'Kansas St.',
  'Kennesaw State': 'Kennesaw St.',
  'Kent State': 'Kent St.',
  'Long Beach State': 'Long Beach St.',
  'Long Island University': 'LIU',
  'Louisiana State': 'LSU',
  'Louisiana-Monroe': 'La.-Monroe',
  'Loyola (IL)': 'Loyola Chicago',
  'Loyola (MD)': 'Loyola Md.',
  'Maryland-Baltimore County': 'UMBC',
  'Maryland-Eastern Shore': 'MD-Eastern Shore',
  'Massachusetts-Lowell': 'UMass Lowell',
  'McNeese State': 'McNeese St.',
  'Miami (FL)': 'Miami Fl.',
  'Miami (OH)': 'Miami Ohio',
  'Michigan State': 'Michigan St.',
  'Middle Tennessee State': 'Middle Tenn.',
  'Mississippi State': 'Mississippi St.',
  'Mississippi Valley State': 'Mississippi Valley St.',
  'Missouri-Kansas City': 'UMKC',
  'Montana State': 'Montana St.',
  'Morehead State': 'Morehead St.',
  'Morgan State': 'Morgan St.',
  'Murray State': 'Murray St.',
  'Nevada-Las Vegas': 'UNLV',
  'New Mexico State': 'New Mexico St.',
  'Nicholls State': 'Nicholls St.',
  'Norfolk State': 'Norfolk St.',
  'North Carolina A&T': 'NC A&T',
  'North Carolina State': 'NC State',
  'North Carolina-Asheville': 'UNC Asheville',
  'North Carolina-Greensboro': 'UNC Greensboro',
  'North Carolina-Wilmington': 'UNC-Wilmington',
  'North Dakota State': 'North Dakota St.',
  'Northwestern State': 'Northwestern St.',
  'Ohio State': 'Ohio St.',
  'Oklahoma State': 'Oklahoma St.',
  'Oregon State': 'Oregon St.',
  'Pennsylvania': 'Penn',
  'Portland State': 'Portland St.',
  'Purdue-Fort Wayne': 'Fort Wayne',
  'Sacramento State': 'Sacramento St.',
  'Saint Francis (PA)': 'St. Francis Pa.',
  'Saint Mary\'s (CA)': 'Saint Mary\'s',
  'Saint Peter\'s': 'St. Peter\'s',
  'Sam Houston State': 'Sam Houston St.',
  'San Diego State': 'San Diego St.',
  'San Jose State': 'San Jose St.',
  'Savannah State': 'Savannah St.',
  'South Carolina State': 'South Carolina St.',
  'South Carolina Upstate': 'USC Upstate',
  'South Dakota State': 'South Dakota St.',
  'Southeast Missouri State': 'SE-Missouri St.',
  'Southeastern Louisiana': 'SE-Louisiana',
  'Southern California': 'USC',
  'Southern Illinois-Edwardsville': 'SIU-Edwardsville',
  'Southern Methodist': 'SMU',
  'Southern Mississippi': 'Southern Miss',
  'St. Francis (NY)': 'St. Francis NY',
  'St. John\'s (NY)': 'St. John\'s',
  'Tennessee State': 'Tennessee St.',
  'Texas-Arlington': 'UT Arlington',
  'Texas-El Paso': 'UTEP',
  'Texas-Rio Grande Valley': 'UT Rio Grande Valley',
  'Texas-San Antonio': 'UTSA',
  'University of California': 'California',
  'Utah State': 'Utah St.',
  'Virginia Commonwealth': 'VCU',
  'Washington State': 'Washington St.',
  'Weber State': 'Weber St.',
  'Wichita State': 'Wichita St.',
  'Wright State': 'Wright St.',
  'Youngstown State': 'Youngstown St.'
}

const topBetMap = {
  'Alabama A&m': 'Alabama A&M',
  'Albany Ny': 'Albany (NY)',
  'Arkansas Little Rock': 'Little Rock',
  'Ark Pine Bluff': 'Arkansas-Pine Bluff',
  'Bethune Cookman': 'Bethune-Cookman',
  'Boston U': 'Boston University',
  'Bowling Green': 'Bowling Green State',
  'BYU': 'Brigham Young',
  'Cal Irvine': 'UC-Irvine',
  'Cal Poly Slo': 'Cal Poly',
  'Cal Riverside': 'UC-Riverside',
  'Cal Santa Barbara': 'UC-Santa Barbara',
  'California': 'University of California',
  'Central Connecticut': 'Central Connecticut State',
  'Charleston Sou': 'Charleston Southern',
  'Charlotte U': 'Charlotte',
  'Cs Bakersfield': 'Cal State Bakersfield',
  'Cs Fullerton': 'Cal State Fullerton',
  'Cs Northridge': 'Cal State Northridge',
  'Coll Of Charleston': 'College of Charleston',
  'Depaul': 'DePaul',
  'Detroit': 'Detroit Mercy',
  'East Tenn State': 'East Tennessee State',
  'Fla Gulf Coast': 'Florida Gulf Coast',
  'Florida A&m': 'Florida A&M',
  'Florida Intl': 'Florida International',
  'Gardner Webb': 'Gardner-Webb',
  'Illinois Chicago': 'Illinois-Chicago',
  'Ipfw': 'Purdue-Fort Wayne',
  'Kennesaw St': 'Kennesaw State',
  'Long Island': 'Long Island University',
  'Loyola Chicago': 'Loyola (IL)',
  'Loyola Maryland': 'Loyola (MD)',
  'Mcneese State': 'McNeese State',
  'Md Baltimore Co': 'Maryland-Baltimore County',
  'Md Eastern Shore': 'Maryland-Eastern Shore',
  'Miami Florida': 'Miami (FL)',
  'Miami Ohio': 'Miami (OH)',
  'Middle Tenn St': 'Middle Tennessee',
  'UMKC': 'Missouri-Kansas City',
  'Mt. St. Mary\'s': 'Mount St. Mary\'s',
  'Nc Asheville': 'North Carolina-Asheville',
  'Nc Greensboro': 'North Carolina-Greensboro',
  'Nc State': 'North Carolina State',
  'Nc Wilmington': 'North Carolina-Wilmington',
  'Nebraska Omaha': 'Omaha',
  'Njit': 'NJIT',
  'No. Colorado': 'Northern Colorado',
  'North Carolina A&t': 'North Carolina A&T',
  'Prairie View A&m': 'Prairie View',
  'Saint Marys Ca': 'Saint Mary\'s (CA)',
  'Sam Houston St': 'Sam Houston State',
  'Se Louisiana': 'Southeastern Louisiana',
  'Se Missouri State': 'Southeast Missouri State',
  'Seattle U': 'Seattle',
  'Siu Edwardsville': 'Southern Illinois-Edwardsville',
  'Southern Miss': 'Southern Mississippi',
  'St. Francis Ny': 'St. Francis (NY)',
  'St. Francis Pa': 'Saint Francis (PA)',
  'St. Johns': 'St. John\'s (NY)',
  'St. Josephs': 'Saint Joseph\'s',
  'St. Peter\'s': 'Saint Peter\'s',
  'Tennessee Martin': 'Tennessee-Martin',
  'Texas A&m': 'Texas A&M',
  'Texas A&m Corpus': 'Texas A&M-Corpus Christi',
  'Texas San Antonio': 'Texas-San Antonio',
  'The Citadel': 'Citadel',
  'UAB': 'Alabama-Birmingham',
  'Uc Davis': 'UC-Davis',
  'Ul - Lafayette': 'Louisiana',
  'Ul - Monroe': 'Louisiana-Monroe',
  'Umass Lowell': 'Massachusetts-Lowell',
  'Usc Upstate': 'South Carolina Upstate',
  'UNLV': 'Nevada-Las Vegas',
  'Ut Rio Grande Valley': 'Texas-Rio Grande Valley',
  'Ut Arlington': 'Texas-Arlington',
  'Utep': 'Texas-El Paso',
  'Va Commonwealth': 'Virginia Commonwealth',
  'VMI': 'Virginia Military Institute',
  'Wisc Green Bay': 'Green Bay',
  'Wisc Milwaukee': 'Milwaukee'
}

module.exports = {
  aksimsDisplayNames,
  topBetMap,
}